### PR TITLE
Add platformio library registration file

### PR DESCRIPTION
**Pull request by moritz89**
Why:

- Enable dependency management in platformio.org

This change addresses the need by:

- Adding the library.json file with relevant metadata

### CODE REVIEW

**Comment by moritz89** [comment]
If you are not interested in maintaining the library in the platformio.org registry, I would take up the task of maintaining it there.

Best regards,
Moritz

**Comment by kaspermarkus** [comment]
I would appreciate this feature as well

@moritz89 Seems to me that you're missing a Wire dependency in your `library.json` file

**Comment by moritz89** [comment]
@kaspermarkus It's been almost a year since I've raised the issue. I'll just publish it myself. I'm also adding a constructor to specify the Wire instance for use on an ESP32.

**Comment by moritz89** [comment]
@kaspermarkus I checked other libraries and they do not include Wire as a dependency. Isn't this the case for build in dependencies that ship with the Arduino SDK?

**Comment by moritz89** [comment]
@kaspermarkus I've published the package and will look to keep it up to date: https://platformio.org/lib/show/11770/EZO%20I2C%20Sensors

**Pull request closed without merging**
